library;

import 'dart:async';
import 'dart:math' as math;
import 'dart:ui';

import 'package:clock/clock.dart';
import 'package:collection/collection.dart';
import 'package:ema_cal_ai/app/colors.dart';
import 'package:ema_cal_ai/enums/enums.dart';
import 'package:ema_cal_ai/models/chart_data.dart';
import 'package:ema_cal_ai/utils/hooks/init_hook.dart';
import 'package:ema_cal_ai/utils/hooks/video_player_controller.dart';
import 'package:fl_chart/fl_chart.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_hooks/flutter_hooks.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:intl/intl.dart' as intl;
import 'package:reactive_forms/reactive_forms.dart';
import 'package:video_player/video_player.dart';

part 'bmi_indicator.dart';
part 'counter_widget.dart';
part 'custom_asset_video_player.dart';
part 'custom_back_button.dart';
part 'custom_bottom_sheet.dart';
part 'custom_date_picker.dart';
part 'custom_dialog.dart';
part 'custom_filled_button.dart';
part 'custom_outlined_button.dart';
part 'custom_tab_bar.dart';
part 'custom_text_field.dart';
part 'dotted_circle_border.dart';
part 'future_custom_filled_button.dart';
part 'loading_indicator.dart';
part 'loading_overlay.dart';
part 'linear_gauge/linear_gauge.dart';
part 'linear_gauge/ruler_widget.dart';
part 'linear_gauge/controller.dart';
part 'linear_gauge/gauge_line_config.dart';
part 'linear_gauge/scroll_physics.dart';
part 'macro_nutrition_plan_card.dart';
part 'node_connection_animation.dart';
part 'options_list.dart';
part 'scanner_overlay_box.dart';
part 'sensitive_field.dart';
part 'time_picker.dart';
part 'water_intake_card.dart';
part 'wheel_picker.dart';
part 'date_chart.dart';
